### ISSUE TITLE
Implement "record-based" display mode

### ISSUE THREAD

**Issue by jacobwegner** [scaife-viewer/sv-mini#35]
For `iliad-word-alignment`, we should use _text parts_ to break lines within each column

For `iliad-sentence-alignment`, we should organize columns by _alignment records_ (similar to the existing sentence alignment widget)

We can hardcode this for now and revisit an ATLAS metadata setting in the future

**Comment by jacobwegner** [comment]
@paltman I updated the data on the ATLAS endpoint at https://explorehomer-spike-duca-8mwdty.herokuapp.com/graphql/

Here is an illustration (does not have the complete query structure you'll need, but hopefully the gist):

[Sample query](https://explorehomer-spike-duca-8mwdty.herokuapp.com/graphql/#query=%7B%0A%20%20textAlignmentChunks(reference%3A%20%22urn%3Acts%3AgreekLit%3Atlg0012.tlg001.perseus-grc2%3A1.1-1.10%22%2C%20alignment_Slug%3A%20%22iliad-sentence-alignment%22)%20%7B%0A%20%20%20%20metadata%20%7B%0A%20%20%20%20%20%20passageReferences%0A%20%20%20%20%7D%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20relations%20%7B%0A%20%20%20%20%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20tokens%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20veRef%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wordValue%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

```
{
  textAlignmentChunks(reference: "urn:cts:greekLit:tlg0012.tlg001.perseus-grc2:1.1-1.10", alignment_Slug: "iliad-sentence-alignment") {
    metadata {
      passageReferences
    }
    edges {
      node {
        relations {
          edges {
            node {
              tokens {
                edges {
                  node {
                    veRef
                    wordValue
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

```

returns

```
{
  "data": {
    "textAlignmentChunks": {
      "metadata": {
        "passageReferences": [
          "urn:cts:greekLit:tlg0012.tlg001.perseus-grc2:1.1-1.10",
          "urn:cts:greekLit:tlg0012.tlg001.perseus-eng3:1.1"
        ]
      },
      "edges": [
        {
          "node": {
            "relations": {
              "edges": [
                {
                  "node": {
                    "tokens": {
                      "edges": [
                        {
                          "node": {
                            "veRef": "1.1.t1",
                            "wordValue": "μῆνιν"
                          }
                        },
                        {
                          "node": {
                            "veRef": "1.1.t2",
                            "wordValue": "ἄειδε"
                          }
                        },
                        {
                          "node": {
                            "veRef": "1.1.t3",
                            "wordValue": "θεὰ"
                          }
                        },
                        {
                          "node": {
                            "veRef": "1.1.t4",
                            "wordValue": "Πηληϊάδεω"
                          }
                        },
                        {
                          "node": {
                            "veRef": "1.1.t5",
                            "wordValue": "Ἀχιλῆος"
                          }
                        }
                      ]
                    }
                  }
                },
                {
                  "node": {
                    "tokens": {
                      "edges": [
                        {
                          "node": {
                            "veRef": "1.1.t1",
                            "wordValue": "The"
                          }
                        },
                        {
                          "node": {
                            "veRef": "1.1.t2",
                            "wordValue": "wrath"
                          }
                        },
                        {
                          "node": {
                            "veRef": "1.1.t3",
                            "wordValue": "sing"
                          }
                        },
                        {
                          "node": {
                            "veRef": "1.1.t4",
                            "wordValue": "goddess"
                          }
                        },
                        {
                          "node": {
                            "veRef": "1.1.t5",
                            "wordValue": "of"
                          }
                        }
                      ]
                    }
                  }
                }
              ]
            }
          }
        },
      ]
    }
  }
}
```

My thinking is that you could use this to recreate something similar to what we have in the current "sentence alignment" display mode, which is blob based.

You would likely still need to query `passageTextParts` to get the text part refs, but each `textAlignmentChunks.edges.node` would be the "break", rather then breaking per text-part.

You can actually A / B with the "old" sentence alignments by toggling display modes if that is helpful.  (I've left the "old" data in the deployment)

Old:
![image](https://user-images.githubusercontent.com/629062/91226319-718ca580-e6ea-11ea-92d6-9c5429eaa946.png)

New:
![image](https://user-images.githubusercontent.com/629062/91226367-823d1b80-e6ea-11ea-8d49-d6a96b141294.png)

**Comment by paltman** [comment]
I'm actually getting something different for:

```
          textAlignmentChunks(reference: $urn, alignment_Slug: $alignmentSlug) {
              metadata {
                passageReferences
              }
              edges {
                node {
                  id
                  relations {
                    edges {
                      node {
                        id
                        tokens {
                          edges {
                            node {
                              id
                              veRef
                              wordValue
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
```
<img width="568" alt="Screen Shot 2020-09-01 at 11 29 37 AM" src="https://user-images.githubusercontent.com/1192/91880972-6e436d80-ec46-11ea-855f-159e01cf953a.png">

**Comment by jacobwegner** [comment]
@paltman can you double check that your query matches this sample (on the new endpoint)?

https://tinyurl.com/y54egvax

It looks like from your screenshot that you are passing the `iliad-word-alignment` slug, and the sample query is passing `iliad-sentence-alignment`

**Comment by paltman** [comment]
@jacobwegner sentence alignment are already broken up though so I'm confused by what to do if we are not doing word alignments with this.

**Comment by jacobwegner** [comment]
To fetch the text part refs you could either do:

A
```
{
  textAlignmentChunks(reference: "urn:cts:greekLit:tlg0012.tlg001.perseus-grc2:1.1-1.7", alignment_Slug: "iliad-sentence-alignment") {
    metadata {
      passageReferences
    }
    edges {
      node {
        id
        relations {
          edges {
            node {
              id
              tokens {
                edges {
                  node {
                    id
                    veRef
                    wordValue
                    textPart {
                      ref
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

or B:

```
{
  passageTextParts(reference: "urn:cts:greekLit:tlg0012.tlg001.perseus-grc2:1.1-1.7") {
    edges {
      node {
        id
        ref
        tokens {
          edges {
            node {
              id
            }
          }
        }
      }
    }
  }
}
```
